Change extension attribute to avoid conflict with the new bundle-app
This change adapts the generated code to work with the new bundle-app.
This is necessary to avoid the following error:
  TypeError: extension.stateObj.enable is not a function